In [4]:
import importlib

class MuZero:
    def __init__(self, game_name, config=None, split_resources_in=1):
        # Load the game and the config from the module with the game name
        try:
            game_module = importlib.import_module("games." + game_name)
            self.Game = game_module.Game
            self.config = game_module.MuZeroConfig()
        except ModuleNotFoundError as err:
            print(
                f'{game_name} is not a supported game name, try "cartpole" or refer to the documentation for adding a new game.'
            )
            raise err


muzero = MuZero("traderdegen")
env = muzero.Game()
env.reset()
env.render()
print("legal actions: ", env.legal_actions())
# env.human_to_action()

# obs = env.get_observation()
# print(obs)

done = False
while not done:
    action = env.human_to_action()
    observation, reward, done = env.step(action)
    print(f"\nAction: {env.action_to_string(action)}\nReward: {reward}")
    env.render()

Slots status: [nan, nan, nan, nan, nan, 0, 0, 0, 0, 0]
step count:  0
legal actions:  [5, 6]


KeyboardInterrupt: Interrupted by user

In [12]:
import numpy as np

np.random.normal(1,0.1,5)

array([0.96709348, 1.00009932, 1.01960862, 1.11089405, 1.1700756 ])

In [19]:
import numpy as np
age_arr = [3.0, np.nan, 7.0, 6.0, 5.0]
ret_arr = np.where(np.isnan(age_arr),0,np.random.normal(1,0.1,5))
ret_arr = ret_arr - np.where(np.isnan(age_arr),0,np.array(age_arr)*0.1)
ret_arr

array([0.70027926, 0.        , 0.29596488, 0.42610648, 0.68202428])

In [2]:
import numpy as np

arr = np.array([1, 0, 2, 0, 3, 0, 4, 5])

# Get the indices of the non-zero elements in arr
nonzero_indices = np.nonzero(arr)[0]

# Increment the non-zero elements by 1
arr[nonzero_indices] += 1

# Print the updated array
print(arr)



[2 0 3 0 4 0 5 6]


In [8]:
import numpy as np

arr = np.zeros(5)

# print (arr)
game = []
for i in range(21):
    
    # if element is non zero, add 1
    arr = np.where(arr != 0, arr + 1, arr)
    if np.any(arr == 0):
        # update the first zero to 1
        arr[np.where(arr == 0)[0][0]] = 1
    # otherwise set the largest element to 0
    else:
        arr[np.argmax(arr)] = 0
    game.append(arr)    
    
game = np.array(game)
print(game)

# calculate the score
# if the element is non zero, add 1 - the element * 0.1
score = np.where(game != 0, 1 - (game**2) * 0.02, 0)
print(score)
print(np.sum(score))

[[1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]
 [5. 4. 3. 2. 1.]
 [0. 5. 4. 3. 2.]
 [1. 6. 5. 4. 3.]
 [2. 0. 6. 5. 4.]
 [3. 1. 7. 6. 5.]
 [4. 2. 0. 7. 6.]
 [5. 3. 1. 8. 7.]
 [6. 4. 2. 0. 8.]
 [7. 5. 3. 1. 9.]
 [8. 6. 4. 2. 0.]
 [9. 7. 5. 3. 1.]
 [0. 8. 6. 4. 2.]
 [1. 9. 7. 5. 3.]
 [2. 0. 8. 6. 4.]
 [3. 1. 9. 7. 5.]
 [4. 2. 0. 8. 6.]
 [5. 3. 1. 9. 7.]]
[[ 0.98  0.    0.    0.    0.  ]
 [ 0.92  0.98  0.    0.    0.  ]
 [ 0.82  0.92  0.98  0.    0.  ]
 [ 0.68  0.82  0.92  0.98  0.  ]
 [ 0.5   0.68  0.82  0.92  0.98]
 [ 0.    0.5   0.68  0.82  0.92]
 [ 0.98  0.28  0.5   0.68  0.82]
 [ 0.92  0.    0.28  0.5   0.68]
 [ 0.82  0.98  0.02  0.28  0.5 ]
 [ 0.68  0.92  0.    0.02  0.28]
 [ 0.5   0.82  0.98 -0.28  0.02]
 [ 0.28  0.68  0.92  0.   -0.28]
 [ 0.02  0.5   0.82  0.98 -0.62]
 [-0.28  0.28  0.68  0.92  0.  ]
 [-0.62  0.02  0.5   0.82  0.98]
 [ 0.   -0.28  0.28  0.68  0.92]
 [ 0.98 -0.62  0.02  0.5   0.82]
 [ 0.92  0.   -0.28  0.28  0.68]
 [ 0.82  0.98 -0.62  0.02  